//npm run dev 

import Head from 'next/head';

import {BsFillMoonStarsFill} from 'react-icons/bs';
import {AiFillGithub, AiFillTwitterCircle, AiFillLinkedin, AiFillYoutube, AiFillMail,
  AiOutlineArrowDown, AiOutlineArrowRight} from 'react-icons/ai';
import Image from 'next/image';
//import keyboard from 'C:/Users/alice/OneDrive/personal-projects/alz/alz-website/public/keyboard.png';
import keyboard from 'public/keyboard.png';
import ybb from 'public/ybb2.png';
import { Inter } from '@next/font/google'
import ProjectCard from '../components/ProjectCard';
import styles from '../styles/Home.module.css'
import {useRef} from 'react';
import Link from 'next/link';
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const ref = useRef<null | HTMLDivElement>(null);

  const handleClick = () => {
    ref.current?.scrollIntoView({behavior: 'smooth'});
  };

  return (
    <div>
      <Head>
        <title>Alice Zhang Personal Website</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=' bg-gradient-to-br from-slate-900 to-violet-700 px-10'>
        <section className='min-h-screen'>
          <nav className='pt-5 pb-3 lg:pb-5 mb-12 flex justify-between'>
            <a className='text-white text-2xl font-ubuntu' href="">
              <span className=' text-cyan-600'>&lt;</span>alz<span className=' text-cyan-600'>&#47;&gt;</span>
            </a>
            <ul className='flex items-center'>
              <li>
                <BsFillMoonStarsFill className='text-white cursor-pointer text-2xl'/>
              </li>
              {/* <li>
                <a className='bg-gradient-to-br from-blue-700 to-cyan-500 text-white px-4 py-2 rounded-md ml-8' href="/commissions">
                  Keyboard Commissions
                </a>
              </li> */}
            </ul>
          </nav>

          <div className='text-center px-10 lg:p-8'>
            <h2 className='text-6xl lg:py-3 text-cyan-400 font-medium font-ubuntu'>Alice Zhang</h2>
            <h3 className='text-white text-3xl md:py-2'>Developer, designer, creator.</h3>
            <p className='text-lg md:py-3 leading-8 text-gray-300'>
              Driven undergraduate student at Carnegie Mellon University with a passion for creating things.
            </p>
          </div>

          <div className='text-5xl flex justify-center gap-16 py-1 text-gray-300'>
            <a href='https://github.com/azhang45'> <AiFillGithub /> </a>
            <a href='https://www.linkedin.com/in/alice-zhang-994145247/'><AiFillLinkedin /></a>
            <a href='mailto:alicenz0063@gmail.com'><AiFillMail /></a>
          </div>

          <div>
            <h2 className='font-ubuntu text-cyan-700 opacity-80 flex justify-center py-1 lg:py-7'><em>Click the space bar in the image below for a surprise!</em></h2>
          </div>

          <div className='relative flex justify-center mx-auto py-1'>
            <Image src = {keyboard} alt = "useMap" useMap = "#spacebar"/>
            <map name = "spacebar">
              <area shape = "rect" coords = "140,130,333,162" alt = "_blank"
                  href = "/setup" />
              
            </map>
          </div>


          <div className='text-5xl flex justify-center text-cyan-300 pb-8 lg:py-10'>
            <AiOutlineArrowDown className={styles.downarrow} onClick={handleClick} />
          </div>

        </section>

        <section className='py-10'>
          <div>
            <h3 ref={ref} className='text-3xl font-ubuntu bg-zinc-700 px-3 md:px-5 lg:px-9 py-1 pr-5 md:pr-28 lg:pr-60 bg-opacity-60 
              text-left rounded-br-full rounded-tl-full text-gray-300' style={{display: "inline"}}>
              <span className='text-sky-400'>alz@DESKTOP-123456:~$</span> cd programming-projects
            </h3>
          </div>

          {/* grid of prog projects */}
          <div>
            <div className=' text-white py-10 px-10 md:px-24 xl:px-32 grid md:grid-cols-2 xl:grid-cols-4 gap-6'>

              {/* project 1 */}
              <ProjectCard
                title="Sunshine Housing"
                description="Apartment search and user management website developed for Sunshine Living."
                label="sunshine-housing.com"
                link="https://sunshine-housing.com"
                fromColor="yellow-400"
                toColor="sky-600"
                linkColor="lime-600"
              />

              {/* project 2 */}
              <ProjectCard
                title="YourBCABus"
                description="Bus-location tracker developed for the ease of BCA students. A Yenowa project."
                label="yourbcabus.com"
                link="https://about.yourbcabus.com"
                fromColor="emerald-900"
                toColor="emerald-500"
                linkColor="emerald-600"
              />

              {/* project 3 */}
              <ProjectCard
                title="TableJet"
                description="Teacher attendance app to easily notify BCA students for when their teachers are absent. A Yenowa project."
                label="tbj.yourbcabus.com"
                link="https://tbj.yourbcabus.com"
                fromColor="purple-600"
                toColor="slate-950"
                linkColor="violet-950"
              />

              {/* project 4 */}
              <ProjectCard
                title="T-Res"
                description="3D version of the Google Chrome dinosaur game, made in Unity3D."
                label="github.com"
                link="https://github.com/azhang45/T-Res"
                fromColor="sky-800"
                toColor="yellow-500"
                linkColor="teal-700"
              />

              <a href="/progproj" className={styles.card} rel="noopener noreferrer">
                <h2 className={inter.className}>
                  <em>See more <span>-&gt;</span></em>
                </h2>
              </a>
            </div>
          </div>
        </section>

        {/* <section className='pb-10'>
          <div>
            <h3 className='text-3xl font-ubuntu bg-zinc-700 px-3 md:px-5 lg:px-9 py-1 pr-5 md:pr-28 lg:pr-60 bg-opacity-60 
              text-left rounded-br-full rounded-tl-full text-gray-300' style={{display: "inline"}}>
              <span className='text-sky-400'>alz@DESKTOP-123456:~$</span> cd other-projects
            </h3>
          </div>
        </section> */}

      </main>
    </div>
  )
}
