import Head from 'next/head';

import {BsFillMoonStarsFill} from 'react-icons/bs';
import {AiFillGithub, AiFillTwitterCircle, AiFillLinkedin, AiFillYoutube, AiOutlineArrowDown} from 'react-icons/ai';
import Image from 'next/image';
//import keyboard from 'C:/Users/alice/OneDrive/personal-projects/alz/alz-website/public/keyboard.png';
import keyboard from 'public/keyboard.png'
// import { Inter } from '@next/font/google'
// import styles from '@/styles/Home.module.css'
import {useRef} from 'react';
// const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const ref = useRef(null);

  const handleClick = () => {
    ref.current?.scrollIntoView({behavior: 'smooth'});
  };

  return (
    <div>
      <Head>
        <title>Alice Zhang Personal Website</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=' bg-indigo-900 px-10'>
        <section className='min-h-screen'>
          <nav className='py-5 mb-12 flex justify-between'>
            <h1 className='text-2xl font-ubuntu'>alz</h1>
            <ul className='flex items-center'>
              <li>
                <BsFillMoonStarsFill className='cursor-pointer text-2xl'/>
              </li>
              <li>
                <a className='bg-gradient-to-br from-blue-700 to-cyan-500 text-white px-4 py-2 rounded-md ml-8' href="#">
                  Resume
                </a>
              </li>
            </ul>
          </nav>

          <div className='text-center p-10'>
            <h2 className='text-6xl py-2 text-cyan-400 font-medium font-ubuntu'>Alice Zhang</h2>
            <h3 className='text-3xl py-2'>Developer, engineer, and songwriter.</h3>
            <p className='text-lg py-5 leading-8 text-gray-300'>
              Driven high school student with a passion for creating things.
            </p>
          </div>

          <div className='text-5xl flex justify-center gap-16 py-3 text-gray-300'>
            <AiFillGithub />
            <AiFillYoutube />
            <AiFillLinkedin />
            <AiFillTwitterCircle />
          </div>

          <div className='relative flex justify-center mx-auto py-10'>
            <Image src={keyboard} />
          </div>

          <div className='text-5xl flex justify-center text-cyan-300'>
            <AiOutlineArrowDown onClick={handleClick} />
          </div>

        </section>

        <section>
          <h3 ref={ref} className='text-3xl font-ubuntu bg-zinc-700 px-3 bg-opacity-70 text-left text-sky-400' style={{display: "inline"}}>
            alz@DESKTOP-123456:~$
            </h3>
            <h3 className='text-3xl font-ubuntu bg-zinc-700 px-3 bg-opacity-70 text-left text-gray-300' style={{display: "inline"}}>
              cd programming-projects
            </h3>
        </section>

      </main>
    </div>
  )
}
